config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'decks#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :decks
  resources :cards

  namespace :api do
    namespace :v1 do
      resources :decks
      resources :cards
      post "place_land" => 'battlefields#place_land'
      post "cast_spell" => 'battlefields#cast_spell'
      post "resolve_permanent" => 'battlefields#resolve_permanent'
      post "resolve_nonpermanent" => 'battlefields#resolve_nonpermanent'
      post "tap_card" => 'battlefields#tap_card'
      post "opponent_draw" => 'battlefields#opponent_draw'
      post "send_land_to_graveyard" => 'battlefields#send_land_to_graveyard'
      post "send_permanent_to_graveyard" => 'battlefields#send_permanent_to_graveyard'
      post "decrease_opponent_life" => 'battlefields#decrease_opponent_life'
    end
  end

  get 'battlefield' => 'decks#battlefield', as: :battlefield
  get 'test' => 'decks#test_pusher'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magic: The Walshening</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script>
  window.setTimeout(function() {
    $(".flash").fadeTo(500, 0).slideUp(500, function(){
      $(this).remove();
    });
  }, 5000);
  </script>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid" id="main-navbar">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="logo" class="navbar-brand" href="/">Magic: the Walshening</a>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="<%= battlefield_path %>">Battlefield</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.nil? %>
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
          <% end %>

          <% if current_user %>
            <li><a href="/users/edit">Edit Profile</a></li>
            <li class="divider"></li>
            <li><a href="/users/sign_out" id="sign_out_link">Sign Out</a></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "col-md-12 absolute alert alert-#{name} flash" %>
    <% end %>

  <%= yield %>

</body>
</html>